### PR TITLE
feat: Add .api syntax, support for multiple routing response docs

### PR DESCRIPTION
**Pull request by csh995426531**
The current api documentation generated by swagger only has examples of successful returns for returns, and lacks support for multiple return formats, add additional annotation syntax to support the feature.
The final result is similar:
image

### CODE REVIEW

**Comment by anqiansong** [comment]
The current syntax structure can meet your needs, the authors of goctl-swagger will support it in subsequent versions, you can create a feature to the goctl-swagger plugin.

**Comment by csh995426531** [comment]
> The current syntax structure can meet your needs, the authors of goctl-swagger will support it in subsequent versions, you can create a feature to the goctl-swagger plugin.
Okay

**Comment by csh995426531** [comment]
> The current syntax structure can meet your needs, the authors of goctl-swagger will support it in subsequent versions, you can create a feature to the goctl-swagger plugin.

Okay, I added a merge to goctl-swagger to parse the content in the comment

**Comment by waltcow** [comment]
😊 it looks good to me

**Pull request closed without merging**
