### PR TITLE
add user middleware chain function

### PR DESCRIPTION
**Pull request by magickeha**
According to different business scenarios, the choice of middleware chain should be user-selectable, and considering performance issues, invalid middleware should be eliminated

### CODE REVIEW

**Comment by kevwan** [comment]
I think it over and over, and don't think let users pass a chain is not easy to understand.

Need more easy-to-understand solution for this.

**Comment by magickeha** [comment]
> I think it over and over, and don't think let users pass a chain is not easy to understand.
> 
> Need more easy-to-understand solution for this.

On the basis of not affecting the functions of the existing framework, it may be a good option to allow users to customize some functions in the middleware processing.
Here is my reason:
1. Users can adjust the order of middleware based on their own business scenarios
2. You can or add your own middleware in
3. Remove the middleware that is not used by itself to avoid invalid judgment
4. When the user does not need custom middleware, the default middleware can be used

**Comment by magickeha** [comment]
> I think it over and over, and don't think let users pass a chain is not easy to understand.
> 
> Need more easy-to-understand solution for this.

If the implementation is not elegant enough, please provide some suggestions, thanks

**Comment by kevwan** [comment]
I'm thinking of the following method:

```go
svr.WithMiddlewares(middlewares ...Middleware)
```

And default middlewares are disabled.

**Comment by kunyu** [comment]
> I'm thinking of the following method:
> 
> ```go
> svr.WithMiddlewares(middlewares ...Middleware)
> ```
> 
> And default middlewares are disabled.

I don't think this way can customize middleware order

**Comment by magickeha** [comment]
> The calling order of the middleware before entering the route is relatively fixed. I think it is also a good choice to determine the execution order of the middleware through the order of the variable parameters passed in.



> > I'm thinking of the following method:
> > ```go
> > svr.WithMiddlewares(middlewares ...Middleware)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And default middlewares are disabled.
> 
> I don't think this way can customize middleware order

The calling order of the middleware before entering the route is relatively fixed. I think it is also a good choice to determine the execution order of the middleware through the order of the variable parameters passed in.

**Review by kevwan — APPROVED** [review]
LGTM

**Pull request merged**
