### PR TITLE
logx conf add DisableStat

### PR DESCRIPTION
**Pull request by mycatone**
logx conf add DisableStat
---------------------------
Log:
  Mode: console
  Path: logs/api
  Level: info
  DisableStat: false

### CODE REVIEW

**Comment by chenquan** [comment]
Why do this? Usually production environments don't stop or enable statistics frequently.

**Comment by chenquan** [comment]
Thank you for submitting the pr, but this feature is not commonly used, so it is not recommended to integrate into the framework, which will increase the complexity of the configuration. Implement it yourself if needed.

**Comment by mycatone** [comment]
The submitted function is a method already implemented by the framework, and only a configuration parameter is added。

**Comment by chenquan** [comment]
> The submitted function is a method already implemented by the framework, and only a configuration parameter is added。

Yes, thank you very much for your PR, it will increase the complexity of the configuration. we'll revisit the issue when there are more voices.

**Review by kevwan — APPROVED** [review]

**Pull request merged**
