### PR TITLE
fix: redis reacquire

### PR DESCRIPTION
**Pull request by seth-shi**
see: TestRedisLock_SameAcquire test

### CODE REVIEW

**Comment by seth-shi** [comment]
locker id just use as release key

**Comment by kevwan** [comment]
Thanks for your contribution! Would you please resolve conflicts?

**Comment by zcong1993** [comment]
go-zero's redis lock is a bit like etcd's lease.
When you first acquire a lock with a TTL, you own the lock, then you can do two things:
1. release the lock
2. refresh TTL of the lock, recall `Acquire` method if you own the lock, same like `keepalive` of etcd's lease

**Comment by seth-shi** [comment]
that' s a good explanation, but I think the lock should be for other language users not to create ambiguity. because distributed locks can't be reowned even by themselves

**Comment by seth-shi** [comment]
a typical example is 'redis set nx ex'
the effect is the same whether it's the same client or a different client call

**Comment by seth-shi** [comment]
new pr: https://github.com/zeromicro/go-zero/pull/4325

**Pull request closed without merging**
