### PR TITLE
feat: support ctx in sqlx/sqlc, listed in ROADMAP

### PR DESCRIPTION
**Pull request by kevwan**

### CODE REVIEW

**Comment by chenquan** [comment]
https://github.com/zeromicro/go-zero/blob/d254e6dc0a53cd03192b038d129ae2f3b44702e8/core/stores/sqlx/sqlconn.go#L240-L247
Maybe  need to judge `context.Canceled` and `context.DeadlineExceeded`?

**Comment by kevwan** [comment]
> https://github.com/zeromicro/go-zero/blob/d254e6dc0a53cd03192b038d129ae2f3b44702e8/core/stores/sqlx/sqlconn.go#L240-L247
> 
> 
> Maybe need to judge `context.DeadlineExceeded` ?

good catch!

**Comment by chenquan** [comment]
https://github.com/zeromicro/go-zero/blob/1131cec070600b3396aafcdf914b1f048da724cd/core/stores/sqlx/tx.go#L128
https://github.com/zeromicro/go-zero/blob/1131cec070600b3396aafcdf914b1f048da724cd/core/stores/sqlx/tx.go#L134

`rollback failed: %s` - > `rollback failed: %w`  more perfect.

**Review by chenquan — APPROVED** [review]
lgtm

**Comment by re-dylan** [comment]
goctl mysql model gen should support context

**Comment by kevwan** [comment]
> goctl mysql model gen should support context

I think it might be better to in another PR. And merge it after go-zero v1.3.1 released, which contains this PR.

Otherwise, if we release another goctl version, it breaks.

**Pull request merged**
