### PR TITLE
generates nested types in doc

### PR DESCRIPTION
**Pull request by zlx362211854**
Provides the ability to generate nested types 
like
```go
type CommonResponse {
	Code    int    `json:"code"` // 100 | 200
	Message string `json:"message"`
}
type UserCreateDto {
	Id string `json:"id"`
}
type UserCreateResponse {
	CommonResponse
	Result *UserCreateDto `json:"result"` // result
}
```

is generate to 
```go

type UserCreateResponse struct  {
	Code    int    `json:"code"` // 100 | 200
	Message string `json:"message"`
	Result struct {
            Id string `json:"id"`
        } `json:"result"` // result
}
```

### CODE REVIEW

**Comment by kevwan** [comment]
How can we know when to be nested or not?

**Comment by zlx362211854** [comment]
image

image

i use this spec.ApiSpec.Types to determine whether it is a golang built-in type,  and if it is, then call `getRefProperty` to generate the nested types

**Review by anqiansong — APPROVED** [review]
LGTM

**Comment by anqiansong** [comment]
Use #2368 instead

**Pull request merged**
