### PR TITLE
add: implemented redis FLUSH commands

### PR DESCRIPTION
**Pull request by Guvanchhojamov**
Implemented:

- FlushAll
- FLushDB
- FLushAllAsync
- FLushDBAsync

For more detail see:  [redis docs](https://redis.io/commands/flushall/)
Thanks!

### CODE REVIEW

**Comment by Guvanchhojamov** [comment]
@gokure

**Comment by kevwan** [comment]
Thanks! But we're not going to support FLUSH command in go-zero.

**Comment by Guvanchhojamov** [comment]
@kevwan. Ok, Thank you.

**Comment by Guvanchhojamov** [comment]
We can close this PR then)

**Comment by kevwan** [comment]
Thanks for contribution! Closing.

**Pull request closed without merging**
