### PR TITLE
Add prefix for cache keys.

### PR DESCRIPTION
**Pull request by xhochipe**
redis默认是db0,很多项目共用redis实例的时候,可能导致redis的key重复，生成cache的时候加上prefix，这个参数可以是当前项目的名字，这样就可以很好的解决共用redis实例的时候，相同的表的redis缓存key一致的情况.eg:cache:system:config:id(old:  cache:config:id)

### CODE REVIEW

**Comment by kesonan** [comment]
A same argument named `database` for mysql and `schema` for pg was supported, so I think this changes maybe duplicate.

**Comment by xhochipe** [comment]
> A same argument named `database` for mysql and `schema` for pg was supported, so I think this changes maybe duplicate.
@kesonan 对于不同的项目来着，如果公用一个redis实例的时候，相同的schema，这时候数据就有可能重复，再比如极端点，id都是自增的，这时候数据就可以混了，或者就是支持redis 的db可以配置，不然很可能出现这样 的情况，我们测试环境就出现了好几起这样的事情

**Comment by kesonan** [comment]
> > A same argument named `database` for mysql and `schema` for pg was supported, so I think this changes maybe duplicate.
> > @kesonan 对于不同的项目来着，如果公用一个redis实例的时候，相同的schema，这时候数据就有可能重复，再比如极端点，id都是自增的，这时候数据就可以混了，或者就是支持redis 的db可以配置，不然很可能出现这样 的情况，我们测试环境就出现了好几起这样的事情
 
I know your business scenario, the parameters `schema` and `database` that have been provided so far are not just literal, it's not a matter of providing as many parameters with as many prefixes as the developer needs, you can add arbitrary strings to control that, or even a single project prefix, so all you need is a prefix that can differentiate between the cache keys.

**Comment by xhochipe** [comment]
> > > A same argument named `database` for mysql and `schema` for pg was supported, so I think this changes maybe duplicate.
> > > @kesonan 对于不同的项目来着，如果公用一个redis实例的时候，相同的schema，这时候数据就有可能重复，再比如极端点，id都是自增的，这时候数据就可以混了，或者就是支持redis 的db可以配置，不然很可能出现这样 的情况，我们测试环境就出现了好几起这样的事情
> 
> I know your business scenario, the parameters `schema` and `database` that have been provided so far are not just literal, it's not a matter of providing as many parameters with as many prefixes as the developer needs, you can add arbitrary strings to control that, or even a single project prefix, so all you need is a prefix that can differentiate between the cache keys.

@kesonan 对，是这样，因为现在redis默认是固定死的，有一个前缀，这样在业务上不会造成各种困扰

**Pull request closed without merging**
