### PR TITLE
feat: add the SIGINT signal in signals.go to subscribe the user input ctrl+c to exit the application operation

### PR DESCRIPTION
**Pull request by Suyghur**
I think it's useful in coding

### CODE REVIEW

**Comment by Suyghur** [comment]
help to code review, plz~ @kevwan

**Comment by kevwan** [comment]
I don't think it's necessary in coding stage. Because if so, interrupting takes couple seconds.

**Comment by Suyghur** [comment]
> I don't think it's necessary in coding stage. Because if so, interrupting takes couple seconds.

it brings the coding stage as close as possible to the pro env

**Comment by Suyghur** [comment]
> I don't think it's necessary in coding stage. Because if so, interrupting takes couple seconds.

it brings the coding stage as close as possible to the pro env

**Comment by kevwan** [comment]
> > I don't think it's necessary in coding stage. Because if so, interrupting takes couple seconds.
> 
> it brings the coding stage as close as possible to the pro env

We might need some discussion. Reply tomorrow. Thanks!

**Review by kevwan — APPROVED** [review]

**Pull request merged**
