### PR TITLE
fix goctl rpc protoc strings.EqualFold Service.Name GoPackage

### PR DESCRIPTION
**Pull request by LeeDF**

### CODE REVIEW

**Comment by LeeDF** [comment]
syntax = "proto3"; 
package pushService;
option go_package="./pushService";
service PushService {}
rpc gen code is conflict

**Comment by kevwan** [comment]
image

It's working from my side. What's the error?

**Comment by LeeDF** [comment]
pushService.proto
```
syntax = "proto3";
package pushService;
option go_package = "./pushService";
message In {
  int64 id = 1;
}
message Out {
  int64 id = 2;
}
service PushService {
  rpc echo(In) returns(Out);
}
```

`
 goctl rpc protoc ./*.proto -I=./   --go_out=./ --go-grpc_out=./ --zrpc_out=./
`
in pushservice directory contains package pushservice and package pushService

**Comment by LeeDF** [comment]
> pushService.proto
> 
> ```
> syntax = "proto3";
> package pushService;
> option go_package = "./pushService";
> message In {
>   int64 id = 1;
> }
> message Out {
>   int64 id = 2;
> }
> service PushService {
>   rpc echo(In) returns(Out);
> }
> ```
> 
> `goctl rpc protoc ./*.proto -I=./ --go_out=./ --go-grpc_out=./ --zrpc_out=./` in pushservice directory contains package pushservice and package pushService

goctl version 1.3.8 darwin/amd64
protoc-gen-go v1.28.0

**Review by anqiansong — APPROVED** [review]
LGTM, I am going to resolve this issue next release,  Great!

**Pull request merged**
