### PR TITLE
feat: upgrade grpc to 1.46

### PR DESCRIPTION
**Pull request by kevwan**
- remove the deprecated grpc.WithBalancerName

### CODE REVIEW

**Review by zhoushuguang — APPROVED** [review]
+LGTM

**Review by Mikaelemmmm — COMMENTED** [review]
so quickly

**Review by fynxiu — COMMENTED** [review]
lgtm

**Review by chenquan — APPROVED** [review]
lgtm 👍

**Comment by kevwan** [comment]
I'll keep an eye on this proposal.

https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md

**Pull request merged**
