### PR TITLE
feat: add publish and subscribe method

### PR DESCRIPTION
**Pull request by Kseng**
- Upgrade Redis to v9 version
- Update RedisNode to use UniversalClient
- Add Redis Publish and Subscribe function
- Update Hook implement to v9 version

### CODE REVIEW

**Comment by kevwan** [comment]
@Kseng Thanks for your contribution! Please fix the CI failure.

**Comment by Kseng** [comment]
> @Kseng Thanks for your contribution! Please fix the CI failure.

Hi @kevwan , fixed the go mod files issue, please check, thanks.

**Comment by kevwan** [comment]
@Kseng Thanks for your contribution!

Would you please rebase the master and update your PR?

I think two major changes are great, use `UniversalClient` and adding `publish` & `subscribe` methods.

**Comment by Kseng** [comment]
> @Kseng Thanks for your contribution!
> 
> It's kind of duplicate with #3088.
> 
> Would you please rebase the master and update your PR?
> 
> I think two major changes are great, use `UniversalClient` and adding `publish` & `subscribe` methods.

Hi @kevwan , done for merge and update, can help review again, thanks.

**Comment by zcong1993** [comment]
> > @Kseng Thanks for your contribution!
> > It's kind of duplicate with #3088.
> > Would you please rebase the master and update your PR?
> > I think two major changes are great, use `UniversalClient` and adding `publish` & `subscribe` methods.
> 
> Hi @kevwan , done for merge and update, can help review again, thanks.

lint ci failed, please run `go mod tidy` and commmit changes.

**Comment by Kseng** [comment]
> > @Kseng Thanks for your contribution!
> > It's kind of duplicate with #3088.
> > Would you please rebase the master and update your PR?
> > I think two major changes are great, use `UniversalClient` and adding `publish` & `subscribe` methods.
> 
> Hi @kevwan , done for merge and update, can help review again, thanks.

Weird, seem don't have any changes in go.mod and i tried to use docker pull latest ubuntu and try to run test-linux command, but result is nothing changes, any idea for this? 

image
image

**Pull request closed without merging**
