### PR TITLE
fix #3375

### LINKED ISSUE #3375: 只要使用 w.(http.Flusher).Flush()，response header就会被重置
image
如图，只要使用了w.(http.Flusher).Flush()，response header就会被重置
image

请求大佬们解决

### PR DESCRIPTION
**Pull request by anyoptional**
re-implement http.Flusher interface for timeout handler, which solves issue #3375

### CODE REVIEW

**Comment by kevwan** [comment]
Thanks for your contribution! But unit test is a must for PR.

**Comment by anyoptional** [comment]
> Thanks for your contribution! But unit test is a must for PR.

Some unit tests have been added, hopefully this helps.

**Comment by kevwan** [comment]
Duplicate of #3388

**Comment by kevwan** [comment]
The solution of #3388 is much simpler. Thanks for your contribution!

**Pull request closed without merging**
