### PR TITLE
Enhanced the CODE_OF_CONDUCT Guidelines

### PR DESCRIPTION
**Pull request by tvermaashutosh**
I have enhanced/improved the CODE_OF_CONDUCT Guidelines via updating the CODE_OF_CONDUCT.md file. Making it more clear/comprehensible for the users, ensuring that users can easily access and understand the CODE_OF_CONDUCT instructions information.
I have also corrected the minor grammatical errors etc. that were present in the file previously.

@kevwan 
Kindly review my PR and merge it please.

### CODE REVIEW

**Comment by kevwan** [comment]
Please update to the official version 2.1.

**Comment by tvermaashutosh** [comment]
> Please update to the official version 2.1.

@kevwan 
I have made the changes as per your request.
Kindly review and merge my PR please.

**Comment by kevwan** [comment]
Please use this one.

https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Comment by tvermaashutosh** [comment]
> Please use this one.
> 
> https://www.contributor-covenant.org/version/2/1/code_of_conduct/

@kevwan 
I have made the changes as per your request.
Kindly review and merge my PR please.

**Comment by kevwan** [comment]
Why not use the content from `https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md` directly? Is there any important changes that we need to notice?

**Comment by tvermaashutosh** [comment]
> Why not use the content from `https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md` directly? Is there any important changes that we need to notice?

@kevwan 
It's right that we can use the `https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md` directly without any major changes.

**Review by kevwan — APPROVED** [review]

**Comment by tvermaashutosh** [comment]
Thankyou @kevwan for merging my pull request.

**Pull request merged**
