### PR TITLE
feat: add detail type mismatch info in number fields check (#3386)

### PR DESCRIPTION
**Pull request by lxy1992**
add a feature I proposed in #3386

### CODE REVIEW

**Comment by chenquan** [comment]
Thank you very much for your PR, please add more test cases.

**Comment by lxy1992** [comment]
> 

Ok, will do it today, thanks for reply

**Comment by lxy1992** [comment]
@chenquan I have add a UT for this function, the coverage is go up

**Comment by zcong1993** [comment]
> @chenquan I have add a UT for this function, the coverage is go up

can you add some non primitive type mismatch cases in UT？

**Pull request merged**
