### PR TITLE
fix(goctl): multi imports the api cause redeclared error in types.go

### PR DESCRIPTION
**Pull request by wjiec**
Now experimental features are turned on by default in Goctl, is this correct?
https://github.com/zeromicro/go-zero/blob/c7dacb01468bad3a21dc34b18eb8635f875fd29c/tools/goctl/pkg/env/env.go#L79-L81

### CODE REVIEW

**Comment by kesonan** [comment]
Plz describe which issue scenario should be fix

**Comment by wjiec** [comment]
Hi @kesonan, you can check the added test cases to understand that the specific scenario is in a gateway that has the following referenced relationship:
```plain
// main.api
import "xxx.api"
import "yyy.api"

// xxx.api
import "common.api"

// yyy.api
import "common.api"
```
Use `goctl api go -api main.api ... `generated `types.go` has redeclared  structs (from common.api).

**Comment by wjiec** [comment]
hi @kesonan @kevwan do you have time to look at this pr?

**Comment by kesonan** [comment]
image
The `master` branch has already fix this issue, pls try with latest version.

**Comment by wjiec** [comment]
Hi @kesonan , I still have this problem with the latest code in master branch, please check the contents of the `internal/types/types.go` file. Screenshots:

image

**Comment by wjiec** [comment]
Sorry, it should be that the title of the PR is not expressed clearly enough, and the redeclared error appears in the `types.go` file.

**Comment by kevwan** [comment]
Is the problem fixed already?

**Comment by wjiec** [comment]
@kevwan Unfortunately the code on master still has this problem now, and this pr is designed to fix it.

**Comment by kesonan** [comment]
pls execute the following cmd `goctl env` and post the output here, now it is already fixed on master.

**Comment by wjiec** [comment]
@kesonan Okay, this is the output of the `goctl env` command
```
GOCTL_OS=darwin
GOCTL_ARCH=arm64
GOCTL_HOME=/Users/jayson/.goctl
GOCTL_DEBUG=False
GOCTL_CACHE=/Users/jayson/.goctl/cache
GOCTL_EXPERIMENTAL=on
GOCTL_VERSION=1.6.3
PROTOC_VERSION=
PROTOC_GEN_GO_VERSION=v1.33.0
PROTO_GEN_GO_GRPC_VERSION=1.3.0
```

btw, something that could potentially have an impact on this is the value of the `GOCTL_EXPERIMENTAL` env, by default, the value of this environment variable is set to On, I'm guessing this is set to Off by default in your environment?

**Comment by wjiec** [comment]
I retested with the latest code on master, as well as executing `goctl api go ...` on the following envs. and the result is still wrong.
```shell
$ env | grep GOCTL
# nothing
$ ./goctl env
GOCTL_OS=darwin
GOCTL_ARCH=arm64
GOCTL_HOME=/Users/jayson/.goctl
GOCTL_DEBUG=False
GOCTL_CACHE=/Users/jayson/.goctl/cache
GOCTL_EXPERIMENTAL=on
GOCTL_VERSION=1.6.3
PROTOC_VERSION=
PROTOC_GEN_GO_VERSION=v1.33.0
PROTO_GEN_GO_GRPC_VERSION=1.3.0
```

**Comment by wjiec** [comment]
Yes, after I executed `. /goctl env -w GOCTL_EXPERIMENTAL=off`, the generated `types.go` is now correct!

**Comment by kevwan** [comment]
@kesonan PTAL.

**Comment by kesonan** [comment]
@wjiec Please add my WeChat account and we can communicate on WeChat. The efficiency here is a bit low. WeChat ID is `KesonAnn`.

**Review by kesonan — APPROVED** [review]
LGTM

**Pull request merged**
