### PR TITLE
fix: fix log output

### PR DESCRIPTION
**Pull request by chenquan**

### CODE REVIEW

**Comment by MarkJoyMa** [comment]
LGTM

**Comment by Kittoa** [comment]
this is okay too
image
Essentially because the memory is destroyed
image

**Comment by chenquan** [comment]
> this is okay too image Essentially because the memory is destroyed image

Yes, the byte slice is reused here, and the data will be overwritten.

**Comment by chenquan** [comment]
This issue exists with `plain` mode in versions 1.4.1 and below, so consider using `json` mode until the new version is released.

**Comment by Kittoa** [comment]
Okey, thanks.

**Pull request merged**
