### PR TITLE
DialProvider to change the datasource at runtime

### PR DESCRIPTION
**Pull request by yogibaba**
Adding a DialProvider with GetDSN function with driverName, datasource which returns an updated datasouce and an error

To get the datasource string at runtime the service context code updates are;

```
func NewServiceContext(c config.Config) *ServiceContext {
	// OLD:
	// return &ServiceContext{
	// 	Config: c,

	// 	RedisClient: redis.New(c.Redis.Host, func(r *redis.Redis) {
	// 		r.Type = c.Redis.Type
	// 		r.Pass = c.Redis.Pass
	// 	}),
	// 	// IdentityRpc: identity.NewIdentity(zrpc.MustNewClient(c.IdentityRpcConf)),

	// 	// UserAuthModel: model.NewUserAuthModel(sqlx.NewMysql(c.DB.DataSource), c.Cache),
	// 	UserModel: model.NewUserModel(sqlx.NewMysql(c.DB.DataSource), c.Cache),
	// }

	// NEW:
	var serviceContext = &ServiceContext{
		Config: c,

		RedisClient: redis.New(c.Redis.Host, func(r *redis.Redis) {
			r.Type = c.Redis.Type
			r.Pass = c.Redis.Pass
		}),
	}

	dialProvider := sqlx.DialProvider{
		Logic: serviceContext,
		GetDSN: func(driverName string, datasource string) (string, error) {
			counter = counter + 1
			switch counter%2 == 0 {
			case true:
				fmt.Printf("-> looklook_usercenter \n")
				return "root:example@tcp(127.0.0.1:3306)/looklook_usercenter?parseTime=true", nil
			case false:
				fmt.Printf("-> looklook_copy \n")
				return "root:example@tcp(127.0.0.1:3306)/looklook_copy?parseTime=true", nil
			}

			fmt.Printf("%+v\n", serviceContext)
			return datasource, nil
		}}

	serviceContext.UserModel = model.NewUserModel(sqlx.NewMysql(c.DB.DataSource, dialProvider), c.Cache)

	return serviceContext
}
```

### CODE REVIEW

**Comment by kevwan** [comment]
Actually, the change breaks the compatibility.

Any better solution on that?

**Comment by yogibaba** [comment]
> Actually, the change breaks the compatibility.
> 
> Any better solution on that?

As the interfaces are private, I would like some inputs on this.

**Comment by yogibaba** [comment]
sample ServiceContext.go
```
var counter int = 0

func NewServiceContext(c config.Config) *ServiceContext {
	var serviceContext = &ServiceContext{
		Config: c,

		RedisClient: redis.New(c.Redis.Host, func(r *redis.Redis) {
			r.Type = c.Redis.Type
			r.Pass = c.Redis.Pass
		}),
	}

	sqlConn := sqlx.NewMysql(c.DB.DataSource, withConnectionProvider())
	serviceContext.UserModel = model.NewUserModel(sqlConn, c.Cache)

	return serviceContext
}

func withConnectionProvider() sqlx.SqlOption {
	return func(conn *sqlx.CommonSqlConn) {
		conn.GetDSN = GetDSN
	}
}

func GetDSN(driverName, datasource string) (string, error) {
	counter = counter + 1
	switch counter%2 == 0 {
	case true:
		fmt.Printf("-> looklook_usercenter \n")
		return "root:example@tcp(127.0.0.1:3306)/looklook_usercenter?parseTime=true", nil
	case false:
		fmt.Printf("-> looklook_copy \n")
		return "root:example@tcp(127.0.0.1:3306)/looklook_copy?parseTime=true", nil
	}

	fmt.Printf("%+v\n", datasource)
	return datasource, nil
}
```

**Comment by fynxiu** [comment]
@yogibaba 
Could you try a solution outside the framework? IMHO, this is a bit anti-pattern.

**Pull request closed without merging**
