### PR TITLE
feature: add a mongo registry option to convert type easier.

### PR DESCRIPTION
**Pull request by POABOB**
Issue #3734.

If users want to convert their custom type to a MongoDB primitive type, they have to define a WithRegistry() function and set up the Encoder/Decoder.

`mongo/mongo.go`
```go
package mongo

// ...

func WithRegistry(registry *bsoncodec.Registry) mon.Option {
	return func(opts *mopt.ClientOptions) {
		opts.SetRegistry(registry)
	}
}

// Mongo type Encoder/Decoder
var MongoDecimalEncoder bsoncodec.ValueEncoderFunc = func(ect bsoncodec.EncodeContext, w bsonrw.ValueWriter, value reflect.Value) error {...}
var MongoDecimalDecoder bsoncodec.ValueDecoderFunc = func(ect bsoncodec.DecodeContext, r bsonrw.ValueReader, value reflect.Value) error {...}
var MongoDateTimeEncoder bsoncodec.ValueEncoderFunc = func(ect bsoncodec.EncodeContext, w bsonrw.ValueWriter, value reflect.Value) error {...}
var MongoDateTimeDecoder bsoncodec.ValueDecoderFunc = func(ect bsoncodec.DecodeContext, r bsonrw.ValueReader, value reflect.Value) error {...}
```

And `RegisterTypeEncoder` and `RegisterTypeDecoder` like below:

`main.go`
```go
package main

// ...

type User struct {
	ID        primitive.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`
	Name      string             `bson:"name,omitempty" json:"name,omitempty"`
	Money     decimal.Decimal    `bson:"money,omitempty" json:"money,omitempty"`
	CreatedAt time.Time          `bson:"created_at,omitempty" json:"created_at,omitempty"`
}

func main() {
	// ...
	registry := bson.NewRegistry()
	registry.RegisterTypeEncoder(reflect.TypeOf(decimal.Decimal{}), mongo.MongoDecimalEncoder)
	registry.RegisterTypeDecoder(reflect.TypeOf(decimal.Decimal{}), mongo.MongoDecimalDecoder)
	registry.RegisterTypeEncoder(reflect.TypeOf(time.Time{}), mongo.MongoDateTimeEncoder)
	registry.RegisterTypeDecoder(reflect.TypeOf(time.Time{}), mongo.MongoDateTimeDecoder)
	opts := mongo.WithRegistry(registry)
	conn := mon.MustNewModel("mongodb://localhost:27017", "test", "collection", opts)

	// find
	var users []User
	err := conn.Find(ctx, &users, bson.D{{}})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(users)
}
```

In order to make this easier, I added a `WithRegister()` function so that users don't need to implement it themselves. I also used a RegisterType struct to store custom types and their respective Encoder/Decoder functions.
In this feature, users only need to define the `Encoder/Decoder` and use `WithRegistry()`.

`mongo/mongo.go`
```go
package mongo

// ...

// No more use
// func WithRegistry(registry *bsoncodec.Registry) mon.Option {
// 	return func(opts *mopt.ClientOptions) {
// 		opts.SetRegistry(registry)
// 	}
// }

// Mongo type Encoder/Decoder
var MongoDecimalEncoder bsoncodec.ValueEncoderFunc = func(ect bsoncodec.EncodeContext, w bsonrw.ValueWriter, value reflect.Value) error {...}
var MongoDecimalDecoder bsoncodec.ValueDecoderFunc = func(ect bsoncodec.DecodeContext, r bsonrw.ValueReader, value reflect.Value) error {...}
var MongoDateTimeEncoder bsoncodec.ValueEncoderFunc = func(ect bsoncodec.EncodeContext, w bsonrw.ValueWriter, value reflect.Value) error {...}
var MongoDateTimeDecoder bsoncodec.ValueDecoderFunc = func(ect bsoncodec.DecodeContext, r bsonrw.ValueReader, value reflect.Value) error {...}
```

`main.go`
```go
package main

// ...

type User struct {
	ID        primitive.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`
	Name      string             `bson:"name,omitempty" json:"name,omitempty"`
	Money     decimal.Decimal    `bson:"money,omitempty" json:"money,omitempty"`
	CreatedAt time.Time          `bson:"created_at,omitempty" json:"created_at,omitempty"`
}

func main() {
	// ...
	registerType := []mon.RegisterType{
		{
			ValueType: reflect.TypeOf(decimal.Decimal{}),
			Encoder:   mongo.MongoDecimalEncoder,
			Decoder:   mongo.MongoDecimalDecoder,
		},
		{
			ValueType: reflect.TypeOf(time.Time{}),
			Encoder:   mongo.MongoDateTimeEncoder,
			Decoder:   mongo.MongoDateTimeDecoder,
		},
	}
	opts := mon.WithRegistry(registerType...)
	conn := mon.MustNewModel("mongodb://localhost:27017", "test", "collection", opts)
	
	// find
	var users []User
	err := conn.Find(ctx, &users, bson.D{{}})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(users)
}
```

### CODE REVIEW

**Comment by kevwan** [comment]
Thanks for your PR!

I recommend not to import decimal package only because of unit test.

**Comment by POABOB** [comment]
Do I need to update the go-zero document that let people know this function?

**Comment by POABOB** [comment]
@kevwan Do I need to do anything extra?

**Review by kevwan — APPROVED** [review]
LGTM.

**Pull request merged**
