### PR TITLE
feat: Add a flag  to whether to generate pb file

### PR DESCRIPTION
**Pull request by wuqinqiang**
https://github.com/zeromicro/go-zero/issues/4078

### CODE REVIEW

**Comment by wuqinqiang** [comment]
@kevwan Hi, Is there any chance we could merge?

**Comment by kesonan** [comment]
Let me take a look.

**Comment by chaozwn** [comment]
> Thanks for your contributation, ignored pb generate could cause program can not running, that's a tool not expected, it maybe cause tool unstable.

in fact, I actually prefer to support buf, but I have an easy way to make goctl support protoc with its own arguments such as `-I`.  overall, I think @wuqinqiang  makes a good point that proto should indeed include some external proto, such as `protovalidate`  link: https://buf.build/bufbuild/protovalidate

image

**Comment by chaozwn** [comment]
> Thanks for your contributation, ignored pb generate could cause program can not running, that's a tool not expected, it maybe cause tool unstable.

我看了一下其实这位老哥代码整体没有问题，可以看下面这张图，实际生成根本没有用到`genGo`返回值，所以不存在你说的对下面生成有影响。
为什么一定要增加skip的功能？因为protoc不能检测外部import和生成代码，导致无法引用外部proto文件。因为我们完全可以用buf cli托管pb和grpc的文件生成，这样子我们就可以直接引入三方的api，比如google，validate相关的。如果跳过pb生成，那么我们在protoc检测生成语法的时候，就会报找不到import的错误。而采用buf，可以使用他自带的buf.yaml deps管理所有的proto依赖，这是个相当不错的优化，实际生成的代码也是可以使用的。其实我认为这个修改可以达成一个新的feature。下面附录下视频。

image

https://github.com/user-attachments/assets/e14219b6-52df-4b20-8dbc-5fe757ab8f27

**Pull request closed without merging**
