### PR TITLE
Improve logging for response bodies

### PR DESCRIPTION
**Pull request by fondoger**
- Add a check for binary content types in log handler
- Replace response body dump with a new function that takes into account binary content types
- Add a check for empty response body

[rest/handler/loghandler.go]
- Add a function to check if content type is binary file or stream
- Add a function to dump response body that takes into account binary content types
- Replace the response body dump with the new function
- Add a check for empty response body ### BEGIN GIT COMMIT BEFORE AMEND

### END GIT COMMIT BEFORE AMEND

### CODE REVIEW

**Comment by fondoger** [comment]
@kevwan Please help to review this PR. Thanks.

**Comment by fondoger** [comment]
@kevwan Please.

**Comment by kevwan** [comment]
Thanks for your PR!

But how to list all the binary content types?

**Comment by fondoger** [comment]
> Thanks for your PR!
> 
> But how to list all the binary content types?

@kevwan It is not possible to list all binary content types. The family of content types is always growing as time goes by. Also, it is not a force requirement for http server developers to return the body content according to the `Content-Type`.

So I only listed a few most common used binary content types in this PR.

**Comment by kevwan** [comment]
I think it's better not to set `verbose` to `true`. Only if you really want, then set to verbose and debug.

**Comment by fondoger** [comment]
> I think it's better not to set `verbose` to `true`. Only if you really want, then set to verbose and debug.

Yes, you are right. I want to debug an issue so I set `verbose=true`. But the logger keeps printing a very long binary logs, which results in all other normal logs were buried in the binary logs. There is no way to hide the logging for a specific handler. So it is better not to print the binary contents. 

Besides, logs for most binary files are a mess when printed in UTF-8 format. It is better to hide these logs for binary files because they're unreadable.

**Comment by fondoger** [comment]
@kevwan What's wrong with this PR? It's still not merged. Do you have better idea for handling such a specific case?

**Comment by kevwan** [comment]
set verbose to false to ignore body logging. binary body is not guaranteed to be all covered.

**Pull request closed without merging**
