### PR TITLE
add customized.tpl for model template

### PR DESCRIPTION
**Pull request by suyhuai**
for #4089

### CODE REVIEW

**Review by suyhuai — COMMENTED** [review]
good

**Comment by loocor** [comment]
@suyhuai  Thanks bro, maybe you can provide the goal and usage of this PR?

**Comment by suyhuai** [comment]
> @suyhuai Thanks bro, maybe you can provide the goal and usage of this PR?

Ok, find it in #4089

**Review by kesonan — APPROVED** [review]
LGTM

**Pull request merged**
